# Lab 01

# Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr2d[0, 1])

2


In [4]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
print(a + b) 
print(a * b) 
print(a ** 2) 

[5 7 9]
[ 4 10 18]
[1 4 9]


In [7]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [12]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [11]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
sum = np.sum(a)
sum

np.int64(6)

In [19]:
mean = np.mean(a)
mean

np.float64(2.0)

In [20]:
max = np.max(b)
max

np.int64(6)

In [21]:
min = np.min(b)
min

np.int64(4)

# Pandas

In [24]:
import pandas as pd

In [25]:
df = pd.DataFrame(
    {
     'Name': ['Alice', 'Bob'], 
     'Age': [25, 30]
    }
)

In [26]:
df

Name  Age
0  Alice   25
1    Bob   30

In [28]:
df['Name'] 

0    Alice
1      Bob
Name: Name, dtype: object

In [29]:
df[['Name', 'Age']] 

Name  Age
0  Alice   25
1    Bob   30

In [30]:
df.loc[1] 

Name    Bob
Age      30
Name: 1, dtype: object

In [31]:
df.iloc[0] 

Name    Alice
Age        25
Name: 0, dtype: object

In [32]:
df.loc[1, 'Age']

np.int64(30)

# TensorFlow